# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDay152():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_day152(self):
        self.driver.get("https://tutorialsninja.com/demo/")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(By.LINK_TEXT, "My Account").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        time.sleep(0.002)
        self.driver.find_element(By.ID, "input-email").click()
        time.sleep(0.002)
        self.driver.find_element(By.ID, "input-email").click()
        self.driver.find_element(By.ID, "input-email").send_keys("q606213@gmail.com")
        self.driver.find_element(By.ID, "input-password").click()
        self.driver.find_element(By.ID, "input-password").send_keys("606960696069213")
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
        time.sleep(0.003)
        elements = self.driver.find_elements(By.LINK_TEXT, "Edit your account information")
        assert len(elements) > 0
        time.sleep(0.005)
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        self.driver.close()